# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('fijo', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('pais', models.CharField(max_length=128)),
                ('ciudad', models.CharField(max_length=128)),
                ('ci', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
