# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('codigocuenta', models.AutoField(primary_key=True, serialize=False)),
                ('llavecuenta', models.CharField(max_length=128)),
                ('codigocliente', models.IntegerField()),
                ('deposito', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechatransaccion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
