# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160427_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigocliente',
            field=models.IntegerField(default=1, verbose_name='auth.User'),
        ),
    ]
