# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160501_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='user',
            field=models.IntegerField(default=1, verbose_name='auth.User'),
        ),
    ]
