# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_cuenta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='codigocliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
